#ifndef RICHEDITORVIEWPART_GLOBAL_H
#define RICHEDITORVIEWPART_GLOBAL_H

#include <QtCore/qglobal.h>

const string RICHEDITORBUNDELNAME("RichEditorViewBundle.dll");

#ifdef RICHEDITORVIEWPART_LIB
# define RICHEDITORVIEWPART_EXPORT Q_DECL_EXPORT
#else
# define RICHEDITORVIEWPART_EXPORT Q_DECL_IMPORT
#endif

#endif // RICHEDITORVIEWPART_GLOBAL_H
