#ifndef MARKDOWNEDITORVIEWPART_GLOBAL_H
#define MARKDOWNEDITORVIEWPART_GLOBAL_H

#include <QtCore/qglobal.h>
#include <boost/shared_ptr.hpp>

using boost::shared_ptr;

#ifdef MARKDOWNEDITORVIEWPART_LIB
# define MARKDOWNEDITORVIEWPART_EXPORT Q_DECL_EXPORT
#else
# define MARKDOWNEDITORVIEWPART_EXPORT Q_DECL_IMPORT
#endif

#endif // MARKDOWNEDITORVIEWPART_GLOBAL_H
