#ifndef HTMLPREVIEWVIEWPART_GLOBAL_H
#define HTMLPREVIEWVIEWPART_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HTMLPREVIEWVIEWPART_LIB
# define HTMLPREVIEWVIEWPART_EXPORT Q_DECL_EXPORT
#else
# define HTMLPREVIEWVIEWPART_EXPORT Q_DECL_IMPORT
#endif

#endif // HTMLPREVIEWVIEWPART_GLOBAL_H
